language: python

php:
  - 2.7

install: "pip install -r requirements.txt"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:couchdb/stable -y
  - sudo apt-get update -y
  - sudo apt-get remove couchdb couchdb-bin couchdb-common -yf
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install couchdb
  - sudo service couchdb start
  - sudo chmod 777 /etc/couchdb/
  - sudo chmod a+w /etc/couchdb/local.ini
  - sudo echo "[httpd]" >> /etc/couchdb/local.ini
  - sudo echo "enable_cors = true" >> /etc/couchdb/local.ini
  - sudo echo "[cors]" >> /etc/couchdb/local.ini
  - sudo echo "origins = *" >> /etc/couchdb/local.ini
  - sudo echo "methods = GET, POST, PUT, DELETE" >> /etc/couchdb/local.ini
  - sudo service couchdb restart

before_script:
  - curl -X PUT localhost:5984/njb_tests

script: python run-tests.py
