language: python

php:
  - 2.7

install: "pip install -r requirements.txt"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:couchdb/stable -y
  - sudo apt-get update -y
  - sudo apt-get remove couchdb couchdb-bin couchdb-common -yf
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install couchdb
  - sudo service couchdb start
  - wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux32.zip
  - unzip chromedriver_linux32.zip
  - export PATH=$PATH:$PWD/chromedriver

before_script:
  - curl -X PUT localhost:5984/_config/httpd/enable_cors -d '"true"'
  - curl -X PUT localhost:5984/_config/cors/origins -d '"*"'
  - curl -X PUT localhost:5984/_config/cors/methods -d '"GET, POST, PUT, DELETE"'
  - curl -X PUT localhost:5984/njb_tests

script: python run-tests.py
