language: python

php:
  - 2.7

install: "pip install -r requirements.txt"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:couchdb/stable -y
  - sudo apt-get update -yq
  - sudo apt-get remove couchdb couchdb-bin couchdb-common -yf
  - sudo rm /etc/couchdb/local.ini
  - sudo ls /etc/couchdb/local.ini
  - sudo apt-get install -Vy couchdb
  - sudo service couchdb start

before_script:
  - curl -X PUT localhost:5984/njb_tests

script: python run-tests.py