language: python

php:
  - 2.7

install: "pip install -r requirements.txt"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export DEBIAN_FRONTEND=noninteractive"
  - sudo add-apt-repository ppa:couchdb/stable -qy
  - sudo apt-get update -qy
  - sudo apt-get install python-software-properties couchdb -qy

services:
  - couchdb

before_script:
  - curl -X PUT localhost:5984/njb_tests

script: python run-tests.py
